# Generated by Django 4.2.4 on 2023-08-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pictures',
            field=models.ImageField(blank=True, null=True, upload_to='users/profile_images'),
        ),
    ]
