# Generated by Django 4.2.4 on 2023-08-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/covers'),
        ),
        migrations.AddField(
            model_name='post',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='posts/profile_images'),
        ),
    ]
